name: portfolio-pdv

services:
  portfolio-pdv-postgres:
    container_name: portfolio-pdv-pg
    networks:
      - internal-network
    image: bitnami/postgresql
    # ports:
    #   - ${DB_EXTERNAL_PORT}:5432
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    env_file:
      - .env
    volumes:
      - portfolio-pdv-pg-data:/data/postgres

  pdv-api:
    container_name: portfolio-pdv-api
    networks:
      - shared-network
      - internal-network
    image: node:20
    volumes:
      - ./pdv-backend:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "cd pdv-backend;
      npm install --force;
      npx prisma generate;
      npm run start:dev"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - portfolio-pdv-postgres
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@portfolio-pdv-pg:5432/${POSTGRES_DATABASE}
    env_file:
      - .env

volumes:
  portfolio-pdv-pg-data:

networks:
  shared-network:
    external: true
  internal-network:
    driver: bridge
