services:
  postgres:
    container_name: pdv-pg
    image: bitnami/postgresql
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pdv-pg-data:/data/postgres

  backend:
    container_name: pdv-backend
    image: node:20
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install --force && npx prisma generate && npm run start:dev"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pdv-pg:5432/${POSTGRES_DB}

volumes:
  pdv-pg-data:
    name: pdv-pg-data

name: pdv
