version: '3.8'

services:
  postgres:
    container_name: pdv-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pdv-pg-data:/data/postgres

volumes:
  pdv-pg-data:
    name: pdv-pg-data

name: pdv
