name: pdv

services:
  pdv-postgres:
    container_name: pdv-pg
    networks:
      - internal-network
    image: bitnami/postgresql
    # ports:
    #   - ${DB_EXTERNAL_PORT}:5432
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - pdv-pg-data:/data/postgres

  pdv-api:
    container_name: pdv-api
    networks:
      - shared-network
      - internal-network
    image: node:20
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install --force && npx prisma generate && npm run start:dev"
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - pdv-postgres
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@pdv-pg:5432/${POSTGRES_DATABASE}

volumes:
  pdv-pg-data:
    name: pdv-pg-data

networks:
  shared-network:
    external: true
  internal-network:
    driver: bridge
